---
---
- name: Update all RPM packages
  hosts: all
  become: yes

  tasks:
    - name: Update all packages to the latest version
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: yes

    - name: Remove unused dependency packages
      ansible.builtin.dnf:
        autoremove: yes

    - name: Install AIDE
      dnf:
        name: AIDE
        state: latest